import { Component, OnInit } from "@angular/core";
import { moviesApi } from "../dataModel/moviesApi.model";
import { HttpClient } from "@angular/common/http";

@Component({
  selector: "app-movie",
  templateUrl: "./movie.component.html",
  styleUrls: ["./movie.component.css"],
})
export class MovieComponent implements OnInit {
  moviesApi: moviesApi[];
  constructor(private http: HttpClient) {}
  searchText = "";

  ngOnInit(): void {
    this.moviesApi = [
      {
        popularity: 181.725,
        vote_count: 558,
        video: false,
        poster_path: "/6vaqTxkRnoGwjeLqyZbVuVR7Snv.jpg",
        id: 443791,
        adult: false,
        backdrop_path: "/fYPiQewg7ogbzro2XcCTACSB2KC.jpg",
        original_language: "en",
        original_title: "Underwater",
        genre_ids: [28, 27, 878, 53],
        title: "Underwater",
        vote_average: 6.5,
        overview:
          "After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.",
        release_date: "2020-01-08",
      },
      {
        popularity: 137.117,
        vote_count: 261,
        video: false,
        poster_path: "/tzCqMCdjWVWFqWnflayCWYiBCOV.jpg",
        id: 42941,
        adult: false,
        backdrop_path: "/oh8diqIewgp0raZpmW5hRgXAS9s.jpg",
        original_language: "en",
        original_title: "30 Days of Night: Dark Days",
        genre_ids: [27, 53],
        title: "30 Days of Night: Dark Days",
        vote_average: 4.8,
        overview:
          "After surviving the incidents in Barrow, Alaska, Stella Olemaun relocates to Los Angeles, where she intentionally attracts the attention of the local vampire population in order to avenge the death of her husband, Eben.",
        release_date: "2010-10-04",
      },
      {
        popularity: 132.614,
        vote_count: 1221,
        video: false,
        poster_path: "/5EufsDwXdY2CVttYOk2WtYhgKpa.jpg",
        id: 570670,
        adult: false,
        backdrop_path: "/uZMZyvarQuXLRqf3xdpdMqzdtjb.jpg",
        original_language: "en",
        original_title: "The Invisible Man",
        genre_ids: [27, 878, 53],
        title: "The Invisible Man",
        vote_average: 7.2,
        overview:
          "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
        release_date: "2020-02-26",
      },
      {
        popularity: 107.201,
        vote_count: 173,
        video: false,
        poster_path: "/t5BeYGF6qhq1oSvrBwoy9Nbb0rE.jpg",
        id: 20701,
        adult: false,
        backdrop_path: null,
        original_language: "en",
        original_title: "Tales from the Darkside: The Movie",
        genre_ids: [35, 14, 27, 53],
        title: "Tales from the Darkside: The Movie",
        vote_average: 6.1,
        overview:
          'The first segment features an animated mummy stalking selected student victims; the second tale tells the story of a "cat from hell" who cannot be killed and leaves a trail of victims behind it; the third story is about a man who witnesses a bizarre killing and promises never to tell what he saw and the "in-between" bit is the story of a woman preparing to cook her newspaper boy for supper.',
        release_date: "1990-05-03",
      },
      {
        popularity: 92.532,
        vote_count: 656,
        video: false,
        poster_path: "/m4IFNmheHcjbLsVWbUq9TIpWL5S.jpg",
        id: 11284,
        adult: false,
        backdrop_path: "/3r0h6wgYDQwv5LQC62fHsUzEqGs.jpg",
        original_language: "en",
        original_title: "Freddy's Dead: The Final Nightmare",
        genre_ids: [35, 27, 53],
        title: "Freddy's Dead: The Final Nightmare",
        vote_average: 5.2,
        overview:
          "Just when you thought it was safe to sleep, Freddy Krueger returns in this sixth installment of the Nightmare on Elm Street films, as psychologist Maggie Burroughs, tormented by recurring nightmares, meets a patient with the same horrific dreams. Their quest for answers leads to a certain house on Elm Street -- where the nightmares become reality.",
        release_date: "1991-09-05",
      },
      {
        popularity: 90.535,
        vote_count: 356,
        video: false,
        poster_path: "/rmflsMjk4lxx2foNUtd1OKWv6vB.jpg",
        id: 514847,
        adult: false,
        backdrop_path: "/qfQ78ZKiouoM2yhAnfNblp9ijQE.jpg",
        original_language: "en",
        original_title: "The Hunt",
        genre_ids: [28, 27, 53],
        title: "The Hunt",
        vote_average: 6.9,
        overview:
          "Twelve strangers wake up in a clearing. They don't know where they are—or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers.",
        release_date: "2020-03-11",
      },
      {
        popularity: 85.004,
        vote_count: 195,
        video: false,
        poster_path: "/cuuI1UVwnoyDoN691Z0bYZrOezx.jpg",
        id: 555974,
        adult: false,
        backdrop_path: "/rpGYHowXtjw37UxdwO1ZcK5E8IN.jpg",
        original_language: "en",
        original_title: "Brahms: The Boy II",
        genre_ids: [27, 9648, 53],
        title: "Brahms: The Boy II",
        vote_average: 6.4,
        overview:
          "After a family moves into the Heelshire Mansion, their young son soon makes friends with a life-like doll called Brahms.",
        release_date: "2020-02-20",
      },
      {
        popularity: 67.807,
        id: 10014,
        video: false,
        vote_count: 925,
        vote_average: 5.8,
        title: "A Nightmare on Elm Street Part 2: Freddy's Revenge",
        release_date: "1985-10-31",
        original_language: "en",
        original_title: "A Nightmare on Elm Street Part 2: Freddy's Revenge",
        genre_ids: [27],
        backdrop_path: "/tJTrNDt1242xe4zlatlZfDMvWjg.jpg",
        adult: false,
        overview:
          "A new family moves into the house on Elm Street, and before long, the kids are again having nightmares about deceased child murderer Freddy Krueger. This time, Freddy attempts to possess a teenage boy to cause havoc in the real world, and can only be overcome if the boy's sweetheart can master her fear.",
        poster_path: "/seEMZxo6bhHWbWPNcBQfsMAk39F.jpg",
      },
      {
        popularity: 60.973,
        vote_count: 133,
        video: false,
        poster_path: "/nAEGEYTjbli3JoFgyrLn3blxDqi.jpg",
        id: 31967,
        adult: false,
        backdrop_path: "/u7ZiRakTdU2NeYIf0CdF1mr0P6D.jpg",
        original_language: "en",
        original_title: "Dante's Inferno: An Animated Epic",
        genre_ids: [28, 12, 16, 27],
        title: "Dante's Inferno: An Animated Epic",
        vote_average: 6.1,
        overview:
          "Dante journeys through the nine circles of Hell -- limbo, lust, gluttony, greed, anger, heresy, violence, fraud and treachery -- in search of his true love, Beatrice. An animated version of the video game of the same name.",
        release_date: "2010-02-09",
      },
      {
        popularity: 52.007,
        vote_count: 6,
        video: false,
        poster_path: "/1UHrZxcewhGydsqrRF5Z6Qgqf6i.jpg",
        id: 617786,
        adult: false,
        backdrop_path: "/lxVf7wzanbz7m0mou7pUhokBYB.jpg",
        original_language: "en",
        original_title: "The Other Lamb",
        genre_ids: [18, 27, 53],
        title: "The Other Lamb",
        vote_average: 7.3,
        overview:
          "A haunting and nightmarish tale that tells the story of Selah, a young girl born into a repressive cult known as the Flock. The members of the Flock – all women and female children– live in a rural compound, and are led by one man, known only as Shepherd. Selah, a daughter who is on the cusp of teenage-hood, is given the great honor of participating in the sacred ritual of the birthing of the lambs – upon which they depend for survival – where she has a shocking and otherworldly experience. She begins to have strange visions that make her question her own reality, and everything the Shepherd has taught her and her sisters.",
        release_date: "2020-04-03",
      },
      {
        popularity: 49.868,
        vote_count: 1934,
        video: false,
        poster_path: "/pIcV8XXIIvJCbtPoxF9qHMKdRr2.jpg",
        id: 338967,
        adult: false,
        backdrop_path: "/3ghImmHdp4RnC3UkL6hpLayclnb.jpg",
        original_language: "en",
        original_title: "Zombieland: Double Tap",
        genre_ids: [28, 35, 27],
        title: "Zombieland: Double Tap",
        vote_average: 7,
        overview:
          "Columbus, Tallahassee, Wichita, and Little Rock move to the American heartland as they face off against evolved zombies, fellow survivors, and the growing pains of the snarky makeshift family.",
        release_date: "2019-10-09",
      },
      {
        popularity: 42.438,
        vote_count: 3607,
        video: false,
        poster_path: "/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
        id: 474350,
        adult: false,
        backdrop_path: "/8moTOzunF7p40oR5XhlDvJckOSW.jpg",
        original_language: "en",
        original_title: "It Chapter Two",
        genre_ids: [18, 14, 27],
        title: "It Chapter Two",
        vote_average: 6.8,
        overview:
          "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
        release_date: "2019-09-04",
      },
      {
        popularity: 41.862,
        vote_count: 561,
        video: false,
        poster_path: "/qCDPKUMX5xrxxQY8XhGVCKO3fks.jpg",
        id: 599975,
        adult: false,
        backdrop_path: "/zETkzgle7c6wAeW11snnVUBp67S.jpg",
        original_language: "en",
        original_title: "Countdown",
        genre_ids: [27, 53],
        title: "Countdown",
        vote_average: 6.4,
        overview:
          "A young nurse downloads an app that tells her she only has three days to live. With time ticking away and a mysterious figure haunting her, she must find a way to save her life before time runs out.",
        release_date: "2019-10-24",
      },
      {
        popularity: 41.231,
        vote_count: 8752,
        video: false,
        poster_path: "/2h00HrZs89SL3tXB4nbkiM7BKHs.jpg",
        id: 348,
        adult: false,
        backdrop_path: "/o6Tgvgm0YrrsI9EdhTOX52kPjKX.jpg",
        original_language: "en",
        original_title: "Alien",
        genre_ids: [27, 878],
        title: "Alien",
        vote_average: 8.1,
        overview:
          "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.",
        release_date: "1979-05-25",
      },
      {
        popularity: 41.108,
        vote_count: 354,
        video: false,
        poster_path: "/uIMOFUeXkx4tcAydLrzGMLTtzRK.jpg",
        id: 465086,
        adult: false,
        backdrop_path: "/h4x5aN52nq78PM8zXD77THhZTB.jpg",
        original_language: "en",
        original_title: "The Grudge",
        genre_ids: [27, 9648],
        title: "The Grudge",
        vote_average: 5.6,
        overview:
          "After a young mother murders her family in her own house, a detective attempts to investigate the mysterious case, only to discover that the house is cursed by a vengeful ghost. Now targeted by the demonic spirits, the detective must do anything to protect herself and her family from harm.",
        release_date: "2020-01-02",
      },
      {
        popularity: 39.804,
        vote_count: 1415,
        video: false,
        poster_path: "/p69QzIBbN06aTYqRRiCOY1emNBh.jpg",
        id: 501170,
        adult: false,
        backdrop_path: "/A1lvRqwbLz0PIs5QyivFVzCarc6.jpg",
        original_language: "en",
        original_title: "Doctor Sleep",
        genre_ids: [18, 14, 27, 53],
        title: "Doctor Sleep",
        vote_average: 7.1,
        overview:
          "Still irrevocably scarred by the trauma he endured as a child at the Overlook, Dan Torrance has fought to find some semblance of peace. But that peace is shattered when he encounters Abra, a courageous teenager with her own powerful extrasensory gift, known as the 'shine'. Instinctively recognising that Dan shares her power, Abra has sought him out, desperate for his help against the merciless Rose the Hat and her followers.",
        release_date: "2019-10-30",
      },
      {
        popularity: 36.452,
        vote_count: 3318,
        video: false,
        poster_path: "/qWOkfCgioLEf3Km9OWva93RYWAc.jpg",
        id: 396535,
        adult: false,
        backdrop_path: "/9EetaShpwcbSfrcvDmaFaNMtVyK.jpg",
        original_language: "ko",
        original_title: "부산행",
        genre_ids: [28, 27, 53],
        title: "Train to Busan",
        vote_average: 7.7,
        overview:
          "Martial law is declared when a mysterious viral outbreak pushes Korea into a state of emergency. Those on an express train to Busan, a city that has successfully fended off the viral outbreak, must fight for their own survival…",
        release_date: "2016-07-20",
      },
      {
        popularity: 35.41,
        vote_count: 1302,
        video: false,
        poster_path: "/vOl6shtL0wknjaIs6JdKCpcHvg8.jpg",
        id: 567609,
        adult: false,
        backdrop_path: "/j8uPZSPjKYzHlN2B4NhPQVWWZ5x.jpg",
        original_language: "en",
        original_title: "Ready or Not",
        genre_ids: [35, 27, 9648, 53],
        title: "Ready or Not",
        vote_average: 6.9,
        overview:
          "A bride's wedding night takes a sinister turn when her eccentric new in-laws force her to take part in a terrifying game.",
        release_date: "2019-08-21",
      },
      {
        popularity: 35.259,
        vote_count: 0,
        video: false,
        poster_path: "/3mWseAYHG3hUEcWNNn5RRo2VUIb.jpg",
        id: 607244,
        adult: false,
        backdrop_path: null,
        original_language: "en",
        original_title: "Cannibal Hookers",
        genre_ids: [27],
        title: "Cannibal Hookers",
        vote_average: 0,
        overview:
          "Kirsten escaped a religious cult but is still living a dangerous life, turning tricks in Hollywood to get by. She crosses paths with the notorious Cannibal Hookers and joins their man-eating ranks. A renegade priest and a bounty hunter are searching the dark recesses of Los Angeles for Kirsten and the cannibal hookers. Will Kirsten and her blood lusting friends survive their predators to prey another night?",
        release_date: "2020-03-03",
      },
      {
        popularity: 34.61,
        vote_count: 10359,
        video: false,
        poster_path: "/Ha5t0J21eyiq6Az1EXzx0iwsGH.jpg",
        id: 72190,
        adult: false,
        backdrop_path: "/qozlZC1q9bsM7PRfdrnhmkweA0n.jpg",
        original_language: "en",
        original_title: "World War Z",
        genre_ids: [28, 18, 27, 878, 53],
        title: "World War Z",
        vote_average: 6.7,
        overview:
          "Life for former United Nations investigator Gerry Lane and his family seems content. Suddenly, the world is plagued by a mysterious infection turning whole human populations into rampaging mindless zombies. After barely escaping the chaos, Lane is persuaded to go on a mission to investigate this disease. What follows is a perilous trek around the world where Lane must brave horrific dangers and long odds to find answers before human civilization falls.",
        release_date: "2013-06-20",
      },
    ];
  }
}
